export const CATCHPHRASES: readonly string[] = [
  "Chasing invoices so you don't have to.",
  "Your cash flow has a rescue team now.",
  "Turning overdue into on-time, one call at a time.",
  "Finding the financing gap before it finds you.",
  "Vendor prices creep. We catch them.",
  "Insurance renewal? We already compared the market.",
  "Receivables recovered. Margin defended.",
  "The survival scan is running. Breathe.",
  "Every dollar late is a dollar we're hunting.",
  "Working capital, located.",
  "Stress-testing your runway so you don't have to.",
  "The rescue queue is moving. Hold tight.",
  "Autonomous ops. Human-grade hustle.",
  "Cash is late. The agent is not.",
  "Survival mode: activated.",
  "Scanning for savings you didn't know existed.",
  "Your books are talking. We're listening.",
  "Financing options, ranked and ready.",
]
